apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todo-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
spec:
  selector:
    app: todo-api
  ports:
    - name: todo-api
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: todo-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: db-postgresql
          envFrom:
            - secretRef:
                name: backend-credentials
      initContainers:
        - name: exec-migrate
          image: todo-api:latest
          imagePullPolicy: Never
          command:
            - "/server"
            - "migrate"
          env:
            - name: DATABASE_HOST
              value: db-postgresql
          envFrom:
            - secretRef:
                name: backend-credentials
      volumes:
        - name: migration-dir
          emptyDir: {}
