syntax = "proto3";

package todo.v1;

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/field_mask.proto";

option go_package = "github.com/kassshi/golang-practice/backend/internal/gen/todo/v1;todov1";
service TodoService {
  rpc CreateTodo(CreateTodoRequest) returns (Todo);
  rpc GetTodo(GetTodoRequest) returns (Todo);
  rpc UpdateTodo(UpdateTodoRequest) returns (Todo);
  rpc DeleteTodo(DeleteTodoRequest) returns (google.protobuf.Empty);
  rpc ListTodos(google.protobuf.Empty) returns (ListTodosResponse);
}

message Todo {
  string name = 1;
  string title = 2 [(buf.validate.field).string = {
    min_len: 1
    max_len: 100
  }];
  string description = 3 [(buf.validate.field).string.max_len = 500];
  Status status = 4 [(buf.validate.field).enum = {
    defined_only: true
    not_in: [0]
  }];
  int64 created_at = 5;
  int64 updated_at = 6;
}

enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_TODO = 1;
  STATUS_IN_PROGRESS = 2;
  STATUS_DONE = 3;
}

message CreateTodoRequest {
  Todo todo = 1 [(buf.validate.field).required = true];
}

message GetTodoRequest {
  string name = 1 [(buf.validate.field).string.min_len = 1];
}

message UpdateTodoRequest {
  Todo todo = 1 [(buf.validate.field).required = true];
  google.protobuf.FieldMask update_mask = 2;
}

message DeleteTodoRequest {
  string name = 1 [(buf.validate.field).string.min_len = 1];
}

message ListTodosResponse {
  repeated Todo todos = 1;
}
