repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  - name: envoy-gateway
    chart: oci://docker.io/envoyproxy/gateway-helm
    version: v1.7.3
    namespace: envoy-gateway-system
    createNamespace: true

  - name: prometheus
    chart: oci://ghcr.io/prometheus-community/charts/prometheus
    version: 29.6.0
    namespace: prometheus

  - name: grafana
    chart: oci://ghcr.io/grafana-community/helm-charts/grafana
    version: 12.4.0
    namespace: grafana
    values:
      - adminPassword: admin
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.prometheus.svc.cluster.local
                access: proxy
                isDefault: true
              - name: tempo
                type: tempo
                url: http://tempo.tempo.svc.cluster.local:3200
              - name: Loki
                type: loki
                url: http://loki.loki.svc.cluster.local:3100
                access: proxy
                jsonData:
                  timeout: 60
                  maxLines: 1000
  - name: tempo
    chart: oci://ghcr.io/grafana-community/helm-charts/tempo
    version: 2.2.0
    namespace: tempo
    createNamespace: true
    values:
      - persistence:
          enabled: true
  - name: loki
    chart: oci://ghcr.io/grafana-community/helm-charts/loki
    version: 17.4.1
    namespace: loki
    createNamespace: true
    values:
      - deploymentMode: Monolithic
      - loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          schemaConfig:
            configs:
              - from: "2024-04-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          storage:
            type: filesystem
          limits_config:
            allow_structured_metadata: true
            volume_enabled: true
      - singleBinary:
          replicas: 1
          sidecar: false
          persistence:
            enabled: true
            size: 5Gi
      - minio:
          enabled: false
      - gateway:
          enabled: false
      - lokiCanary:
          enabled: false
      - test:
          enabled: false
      - chunksCache:
          enabled: false
      - resultsCache:
          enabled: false
      - backend:
          replicas: 0
      - read:
          replicas: 0
      - write:
          replicas: 0
      - ingester:
          replicas: 0
      - querier:
          replicas: 0
      - queryFrontend:
          replicas: 0
      - queryScheduler:
          replicas: 0
      - distributor:
          replicas: 0
      - compactor:
          replicas: 0
      - indexGateway:
          replicas: 0
      - bloomPlanner:
          replicas: 0
      - bloomBuilder:
          replicas: 0
      - bloomGateway:
          replicas: 0
  - name: opentelemetry-collector
    chart: open-telemetry/opentelemetry-collector
    values:
      - image:
          repository: otel/opentelemetry-collector-k8s
      - mode: daemonset
      - namespaceOverride: opentelemetry
      - presets:
          kubernetesAttributes:
            enabled: true
          logsCollection:
            enabled: true
      - service:
          enabled: true
      - config:
          exporters:
            debug: {}
            otlp/tempo:
              endpoint: http://tempo.tempo.svc.cluster.local:4317
              tls:
                insecure: true
            otlphttp/loki:
              endpoint: http://loki.loki.svc.cluster.local:3100/otlp
          service:
            pipelines:
              traces:
                exporters:
                  - debug
                  - otlp/tempo
              logs:
                exporters:
                  - debug
                  - otlphttp/loki
