repositories:
  - name: open-telemetry
    url: https://open-telemetry.github.io/opentelemetry-helm-charts

releases:
  - name: envoy-gateway
    chart: oci://docker.io/envoyproxy/gateway-helm
    version: v1.7.3
    namespace: envoy-gateway-system
    createNamespace: true

  - name: prometheus
    chart: oci://ghcr.io/prometheus-community/charts/prometheus
    version: 29.6.0
    namespace: prometheus

  - name: grafana
    chart: oci://ghcr.io/grafana-community/helm-charts/grafana
    version: 12.4.0
    namespace: grafana
    values:
      - adminPassword: admin
      - datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Prometheus
                type: prometheus
                url: http://prometheus-server.prometheus.svc.cluster.local
                access: proxy
                isDefault: true
  - name: opentelemetry-collector
    chart: open-telemetry/opentelemetry-collector
    values:
      - image:
          repository: otel/opentelemetry-collector-k8s
      - mode: daemonset
      - namespaceOverride: opentelemetry
      - presets:
          kubernetesAttributes:
            enabled: true
      - service:
          enabled: true
