apiVersion: v1
kind: Namespace
metadata:
  name: todo-api
  labels:
    name: todo-api
    envoy-gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-spa
  labels:
    name: todo-spa
    envoy-gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway
  labels:
    name: envoy-gateway
    envoy-gateway-access: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
  labels:
    name: prometheus
    envoy-gateway-access: "true"
