apiVersion: v1
kind: Namespace
metadata:
  name: todo-api
  labels:
    name: todo-api
---
apiVersion: v1
kind: Namespace
metadata:
  name: todo-spa
  labels:
    name: todo-spa
---
apiVersion: v1
kind: Namespace
metadata:
  name: envoy-gateway
  labels:
    name: envoy-gateway
