// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTodo(ctx context.Context, arg DeleteTodoParams) error
	GetTodoByID(ctx context.Context, arg GetTodoByIDParams) (Todo, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListTodosByUserID(ctx context.Context, userID pgtype.UUID) ([]Todo, error)
	UpdateTodoStatus(ctx context.Context, arg UpdateTodoStatusParams) error
}

var _ Querier = (*Queries)(nil)
